name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
      - hybrid

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version:
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
      # at most 20 concurrent jobs per free account
      # cf. https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#usage-limit
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - run: emacs --version
    - run: make

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # emacs_version:
          # the emacs version in Ubuntu 18.04 LTS
          # - 25.2
          # the emacs version in Debian Buster
          # - 26.1
          # the emacs version in Debian Sid
          # - 26.3
        coq_version:
          - 8.11
        ocaml_version:
          - 4.07-flambda
      # at most 20 concurrent jobs per free account
      # cf. https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#usage-limit
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    # - uses: purcell/setup-emacs@master
    #   with:
    #     version: ${{ matrix.emacs_version }}
    - uses: erikmd/docker-coq-action@alpha
      id: docker-coq-action
      with:
        opam_file: 'dummy.opam'
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: ${{ matrix.ocaml_version }}
        custom_script: |
          startGroup Print opam config
            opam config list; opam repo list; opam list
          endGroup
          startGroup Install emacs
            sudo apt-get update -y -q
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q --no-install-recommends emacs
          endGroup
          startGroup Run tests
            ./ci/test.sh
          endGroup
